Fix has_fit_methods
LAMPSPUC/StateSpaceModels.jl pull request #180
Opened 2020-09-07 15:56 UTC by raphaelsaavedra

Currently the `hasmethod` calls are not doing anything, the function always returns `true`

2020-09-07 19:33 UTC, guilhermebodin requested changes

2020-09-07 19:33 UTC, guilhermebodin commented on src/models/common.jl
> +    m5 = hasmethod(update!, tuple_with_model_type)
`update!` was too vague as a function name. I changed it to:
`fill_model_system!(model::StateSpaceModel)` and
`fill_model_filter!(filter::KalmanFilter, model::StateSpaceModel)`

2020-09-08 09:44 UTC, raphaelsaavedra commented on src/models/common.jl
> +    m5 = hasmethod(update!, tuple_with_model_type)
Only ARIMA and regression have `fill_model_filter!`, so I assume that's not a necessary fit method. I'll change `update!` to `fill_model_system!`

2020-09-08 09:46 UTC, raphaelsaavedra commented on src/models/common.jl
> +    m5 = hasmethod(update!, tuple_with_model_type)
By the way, some models have `update!` and others have `fill_model_filter!`. I assume this is an error? I'll change the remaining updates to `fill_model_filter!`. This should be failing some test, but apparently isn't.

2020-09-08 11:59 UTC, guilhermebodin commented on src/models/common.jl
> +    m5 = hasmethod(update!, tuple_with_model_type)
the models with `update!` are not working

2020-09-08 11:59 UTC, guilhermebodin approved these changes

2020-09-08 12:00 UTC, raphaelsaavedra commented on src/models/common.jl
> +    m5 = hasmethod(update!, tuple_with_model_type)
oh okay, then we should add that to the 0.4 milestones

2020-09-08 12:02 UTC, merged