WIP: Changes to public API
LAMPSPUC/StateSpaceModels.jl pull request #191
Opened 2020-09-15 16:29 UTC by raphaelsaavedra

For readability and searching purposes, I'm moving all exported functions to the main source file. This way it's easy to see which functions are public API and which are not.

This also shows how we have an excessive amount of functions being exported (for example, I don't see why `get_minimizer_hyperparameter_position` or `covariance_one_step_ahead_predictions` need to be exported). 

I also think some of these functions could be renamed as getter functions to make things clearer - e.g. `covariance_filtered_estimates` could become `get_filtered_covariance`.

2020-09-15 17:39 UTC, guilhermebodin approved these changes

2020-09-15 19:02 UTC, guilhermebodin approved these changes

2020-09-16 15:01 UTC, guilhermebodin requested changes
You should add tests for this errors in the getters

2020-09-16 16:50 UTC, raphaelsaavedra commented
I think this is good now. I set `isfitted` to check if there is any hyperparameter with a `NaN` value. I think this is probably the best way to check if a model is fitted? I wanted a way that allows for a model to be considered fitted even if `fit!` wasn't called, e.g., if the user fixed all the hyperparameters.

2020-09-16 19:20 UTC, guilhermebodin approved these changes

2020-09-16 19:59 UTC, merged