Fix arima
LAMPSPUC/StateSpaceModels.jl pull request #218
Opened 2020-12-02 14:48 UTC by guilhermebodin

2020-12-02 14:54 UTC, raphaelsaavedra commented on src/hyperparameters.jl
> +        end
```suggestion
        isnan(get_constrained_value(model, k)) && update_constrained_value!(model, k, v)
```
Can do it in one line

2020-12-02 14:54 UTC, raphaelsaavedra commented on src/models/arima.jl
> +    # TODO must check but I am almost sure (Guilherme)
Want to wait until you're sure before we merge?

2020-12-02 20:22 UTC, guilhermebodin commented on src/hyperparameters.jl
> +        end
I think the one above is more clear...

2020-12-02 20:22 UTC, guilhermebodin commented on src/models/arima.jl
> +    # TODO must check but I am almost sure (Guilherme)
Now I am sure

2020-12-02 20:23 UTC, guilhermebodin commented
My heuristic failed on 1.5 and I don`t know exactly why

2020-12-03 11:20 UTC, raphaelsaavedra commented
There is a simulation in the test, so there is some randomness. The RNG changed in 1.5, so it might be that. Maybe just try changing the seed?

2020-12-06 18:03 UTC, guilhermebodin commented
The problem was the heuristic itself, I took one from other ARIMA packages now.

2020-12-06 18:15 UTC, raphaelsaavedra requested changes
Add compat entry for `ShiftedArrays` and I think it's all good

2020-12-06 18:32 UTC, merged