Update documentation everywhere
LAMPSPUC/StateSpaceModels.jl pull request #226
Opened 2020-12-16 14:16 UTC by guilhermebodin

2020-12-16 15:03 UTC, raphaelsaavedra requested changes

2020-12-16 15:03 UTC, raphaelsaavedra commented on src/hyperparameters.jl
> +    is_fitted(model::StateSpaceModel) -> Bool
I think this moves away from usual julia notation (`iszero`, `iseven`, `isempty`, ...)

2020-12-16 15:03 UTC, raphaelsaavedra commented on src/kalman_filter_and_smoother.jl
> +    get_filtered_state_variance
I prefer the old version because the new one is very long, but that's mostly personal taste.

2020-12-16 15:03 UTC, raphaelsaavedra commented on test/prints.jl
> +@testset "Prints" begin
What is this testing? Perhaps use `@test sprint(show, ...) == ...`?

2020-12-16 18:47 UTC, guilhermebodin commented on docs/src/manual.md
> +StateSpaceModels.jl lets user define in an easy manner a tailor made filter. TODO docs here
Not now... Maybe some day next week.

2020-12-16 18:48 UTC, guilhermebodin commented on test/prints.jl
> +@testset "Prints" begin
I think this might change over time, I am just trying to make sure that the print is not breaking

2020-12-16 18:49 UTC, guilhermebodin commented on src/kalman_filter_and_smoother.jl
> +    get_filtered_state_variance
We can make an adittional function like this
```julia
get(kf, :P)
get(kf, :Ptt)
get(kf, :a)
get(kf, :F)
```

2020-12-17 17:49 UTC, raphaelsaavedra commented on src/kalman_filter_and_smoother.jl
> +    get_filtered_state_variance
I'm not a fan tbh... mostly because it would get to a point where we're basically just using `getproperty` from Base.

2020-12-17 19:37 UTC, merged